defaultItems: # Default items for some things
  GUI:
    filler:
      item: 'STAINED_GLASS_PANE:15'
      name: '&r'
      lore: []
      glow: true
    pageInfo:
      item: 'PAPER'
      name: '&6&lINFO'
      lore:
        - ''
        - '&e{current}&7/&6{max}'
        - ''
    nextPage:
      item: 'ARROW'
      name: '&9Próxima Página'
      lore:
        - ''
        - '&7Clique aqui para ir para a próxima página'
        - ''
    backPage:
      item: 'ARROW'
      name: '&9Página Anterior'
      lore:
        - ''
        - '&7Clique aqui para ir para a página anterior'
        - ''
    loading:
      item: 'PAPER'
      name: '&9Carregando Informações'
      lore:
        - ''
        - '&7Por-favor aguarde'
        - ''
    error:
      item: 'BEDROCK'
      name: '&4&lERRO!'
      lore:
        - ''
        - '&7Algo inesperado aconteceu.'
        - '&7Por-favor tente novamente.'
        - ''

messages:
  "yes": "&aSIM"
  "no": "&cNÃO"
  cooldown: "&4&lERRO! &cVocê precisa aguardar &e@cooldown &csegundo@s para realizar esta ação novamente!"
  unexpectedError: "&4&lERRO! &cUm erro inesperado aconteceu. Por-favor tente novamente."
  leakPermission: "&4&lERRO! &cVocê não possui permissão para utilizar este comando!"
  onlyPlayer: "&4&lERRO! &cApenas jogadores podem utilizar este comando!"
  playerNotFound: "&4&lERRO! &cJogador não encontrado!"
  selectionNotFound: "&4&lERRO! &cVocê não possui nenhuma entidade selecionada!"
  invalidUUID: "&4&lERRO! &cUUID inválido!"
  invalidNumber: "&4&lERRO! &cNúmero inválido!"
  invalidItem: "&4&lERRO! &cItem inválido!"
  successOperation: "&2&lSUCESSO! &aOperação realizada com sucesso!"
  dracoCoreNeeded: "&4&lERRO! &cEsta função necessita do mod DracoCore!"

# These only need to be changed if you want to translate something
time:
  month: "mês"
  months: "meses"
  week: "semana"
  weeks: "semanas"
  day: "dia"
  days: "dias"
  hour: "hora"
  hours: "horas"
  minute: "minuto"
  minutes: "minutos"
  second: "segundo"
  seconds: "segundos"
  and: " e "
dayOfWeek:
  MONDAY:
  - "segunda-feira"
  - "segunda"
  TUESDAY:
  - "terça-feira"
  - "terça"
  - "terca-feira" # typos
  - "terca"
  WEDNESDAY:
  - "quarta-feira"
  - "quarta"
  THURSDAY:
  - "quinta-feira"
  - "quinta"
  FRIDAY:
  - "sexta-feira"
  - "sexta"
  SATURDAY:
  - "sábado"
  SUNDAY:
  - "domingo"

# ResourcePack URL for /texture command
resourcePackURL: ""