name: DracoUtils
main: com.github.oDraco.DracoUtils
version: 1.0
description: Utils plugin I've made to use for my others plugins ;)
depend:
  - NBTAPI
softdepend:
  - HolographicDisplays
commands:
  dracoutils:
    description: Main command
    aliases: dracoutil
  luz:
    description: Enables/disable night vision