name: DracoUtils
main: com.github.oDraco.DracoUtils
version: 1.2
description: Utils plugin I've made to use for my others plugins ;)
depend:
  - NBTAPI
softdepend:
  - WorldEdit
  - mactionbarapi
commands:
  dracoutils:
    description: Main command
    aliases:
      - dracoutil
      - dutil
      - dutils
      - du
      - dracou
  luz:
    description: Enables/disable night vision
  lixeira:
    description: Opens the trashcan
    aliases:
      - lixo
      - trash
  resourcepack:
    description: Downloads the texture pack
    aliases:
      - texture
      - textura
      - texturepack